// Resolves the admin token used for:
//   - HMAC-signing session cookies (auth.js)
//   - bearer-token recovery / cron auth
//   - deriving the AES-GCM key for the secret vault (secret_vault.js)
//
// Lookup order:
//   1. env.ADMIN_TOKEN — set as a Pages secret. Preserves the original
//      CLI flow (setup.sh writes it via `wrangler pages secret put`).
//   2. settings.admin_token — generated by /api/setup on first run.
//      Used by the one-click deploy flow where the operator never
//      touches Pages secrets directly.
//
// We cache the result on the env object for the isolate lifetime so
// downstream calls don't re-hit D1 for every request.

import { loadSettings } from './settings.js';

const CACHE_KEY = '__ps_admin_token_cache';

export async function getAdminToken(env) {
  if (env?.[CACHE_KEY]) return env[CACHE_KEY];
  const fromPagesSecret = env?.ADMIN_TOKEN && String(env.ADMIN_TOKEN).trim();
  if (fromPagesSecret) {
    try { env[CACHE_KEY] = fromPagesSecret; } catch { /* env is frozen on some platforms */ }
    return fromPagesSecret;
  }
  // Fallback: D1-stored token (one-click deploy path).
  if (!env?.DB) return '';
  try {
    const s = await loadSettings(env);
    const tok = String(s?.admin_token || '').trim();
    if (tok) {
      try { env[CACHE_KEY] = tok; } catch { /* ditto */ }
      return tok;
    }
  } catch { /* settings table may not exist yet on a truly fresh deploy */ }
  return '';
}
